---
- name: Déployer l'application Flask avec PostgreSQL et Nginx
  hosts: all
  become: yes
  gather_facts: true
  vars:
    repo_url: "https://github.com/EkinL/TEMPS.git"
    app_dir: "/opt/flask_app"
    venv_path: "{{ app_dir }}/venv"
    flask_app_port: 8000
    db_name: "name"
    db_user: "app_db_user"
    db_password: "app_db_password"
  tasks:
    - name: Vérifier si python3 est installé
      command: python3 --version
      register: python3_check
      ignore_errors: yes
      changed_when: false

    - name: Afficher la version de python3
      debug:
        msg: "Python3 est installé: {{ python3_check.stdout }}"
      when: python3_check.rc == 0

    - name: Installer python3 et python3-pip si python3 n'est pas installé
      apt:
        name:
          - python3
          - python3-pip
        state: present
      when: python3_check.rc != 0

    - name: Vérifier si pip3 est installé
      command: pip3 --version
      register: pip3_check
      ignore_errors: yes
      changed_when: false

    - name: Afficher la version de pip3
      debug:
        msg: "pip3 est installé: {{ pip3_check.stdout }}"
      when: pip3_check.rc == 0

    - name: Installer python3-pip si pip3 n'est pas installé
      apt:
        name: python3-pip
        state: present
      when: pip3_check.rc != 0

- hosts: all
  become: yes
  gather_facts: true
  tasks:
    - name: Vérifier que SQLAlchemy est installé
      command: python3 -c "import sqlalchemy; print(sqlalchemy.__version__)"
      register: sqlalchemy_check
      ignore_errors: yes
      changed_when: false

    - name: Afficher la version de SQLAlchemy si installé
      debug:
        msg: "SQLAlchemy est installé, version: {{ sqlalchemy_check.stdout }}"
      when: sqlalchemy_check.rc == 0

    - name: Installer SQLAlchemy si non installé
      pip:
        name: SQLAlchemy
      when: sqlalchemy_check.rc != 0

- hosts: all
  become: yes
  gather_facts: true
  tasks:
    - name: Vérifier que Flask est installé
      command: python3 -c "import flask; print(flask.__version__)"
      register: flask_check
      ignore_errors: yes
      changed_when: false

    - name: Afficher la version de Flask si installé
      debug:
        msg: "Flask est installé, version: {{ flask_check.stdout }}"
      when: flask_check.rc == 0

    - name: Installer Flask si non installé
      pip:
        name: Flask
      when: flask_check.rc != 0

- hosts: all
  become: yes
  gather_facts: true
  tasks:
    - name: Vérifier si PostgreSQL est installé
      command: psql --version
      register: psql_check
      ignore_errors: yes
      changed_when: false

    - name: Afficher la version de PostgreSQL si est installé
      debug:
        msg: "PostgreSQL est installé: {{ psql_check.stdout }}"
      when: psql_check.rc == 0

    - name: Installer PostgreSQL si non installé
      apt:
        name: postgresql
        state: present
        update_cache: yes
      when: psql_check.rc != 0

    - name: Collecter les informations sur les services
      service_facts:

    - name: Vérifier que le service PostgreSQL est en fonctionnement
      debug:
        msg: "Le service PostgreSQL est en fonctionnement"
      when: "'postgresql' in ansible_facts.services and ansible_facts.services['postgresql'].state == 'running'"

    - name: Démarrer et activer PostgreSQL s'il n'est pas en fonctionnement
      service:
        name: postgresql
        state: started
        enabled: yes
      when: "'postgresql' not in ansible_facts.services or ansible_facts.services['postgresql'].state != 'running'"

- hosts: all
  become: yes
  gather_facts: true
  tasks:
    - name: Vérifier si Docker est installé
      command: docker --version
      register: docker_version
      ignore_errors: yes
      changed_when: false

    - name: Afficher la version de Docker
      debug:
        msg: "Docker est installé: {{ docker_version.stdout }}"
      when: docker_version.rc == 0

    - name: Installer Docker si non installé
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: docker_version.rc != 0

    - name: Récupérer les informations sur les services
      service_facts:

    - name: Vérifier que le service Docker est en fonctionnement
      debug:
        msg: "Le service Docker est en fonctionnement."
      when: "'docker' in ansible_facts.services and ansible_facts.services['docker'].state == 'running'"

    - name: Démarrer et activer Docker si non lancé
      service:
        name: docker
        state: started
        enabled: yes
      when: "'docker' not in ansible_facts.services or ansible_facts.services['docker'].state != 'running'"

    - name: Afficher des informations sur Docker
      command: docker info
      register: docker_info
      ignore_errors: yes
      changed_when: false

    - name: Afficher le résultat de docker info
      debug:
        msg: "Docker info: {{ docker_info.stdout }}"
      when: docker_info.rc == 0

- hosts: all
  become: yes
  gather_facts: true
  tasks:
    - name: Vérifier si Nginx est installé
      command: nginx -v
      register: nginx_check
      ignore_errors: yes
      changed_when: false

    - name: Afficher la version de Nginx
      debug:
        msg: "Nginx est installé: {{ nginx_check.stderr }}"
      when: nginx_check.rc == 0

    - name: Installer Nginx si non installé
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: nginx_check.rc != 0

    - name: Cloner le dépôt GitHub contenant le code
      git:
        repo: repo_url
        dest: "/var/www/temps"
        version: main
        force: yes

    - name: Créer le fichier de configuration Nginx pour l'application
      copy:
        dest: /etc/nginx/sites-available/temps
        content: |
          server {
                  listen 80 default_server;
                  listen [::]:80 default_server;

                  root /var/www/{{ document_root }};

                  # Add index.php to the list if you are using PHP
                  index index.html index.htm index.nginx-debian.html;

                  server_name {{ hostname }};

                  location / {
                          # First attempt to serve request as file, then
                          # as directory, then fall back to displaying a 404.
                          try_files $uri $uri/ =404;
                  }

                  # pass PHP scripts to FastCGI server
                  #
                  #location ~ \.php$ {
                  #       include snippets/fastcgi-php.conf;
                  #
                  #       # With php-fpm (or other unix sockets):
                          fastcgi_pass unix:/run/php/php7.4-fpm.sock;
                  #       # With php-cgi (or other tcp sockets):
                  #       fastcgi_pass 127.0.0.1:9000;
                  #}

                  # deny access to .htaccess files, if Apache's document root
                  # concurs with nginx's one
                  #
                  #location ~ /\.ht {
                  #       deny all;
                  #}
          }


          # Virtual Host configuration for example.com
          #
          # You can move that to a different file under sites-available/ and symlink that
          # to sites-enabled/ to enable it.
          #
          #server {
          #       listen 80;
          #       listen [::]:80;
          #
          #       server_name example.com;
          #
          #       root /var/www/example.com;
          #       index index.html;
          #
          #       location / {
          #               try_files $uri $uri/ =404;
          #       }
          #}
      notify: Reload Nginx

    - name: Activer la configuration Nginx
      file:
        src: /etc/nginx/sites-available/temps
        dest: /etc/nginx/sites-enabled/temps
        state: link
        force: yes

    - name: Récupérer les informations sur les services
      service_facts:

    - name: Démarrer et activer Nginx si ce n'est pas en cours d'exécution
      service:
        name: nginx
        state: started
        enabled: yes
      when: "'nginx' not in ansible_facts.services or ansible_facts.services['nginx'].state != 'running'"

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
