- name: Installation de Python3 et pip3
  hosts: all
  become: yes
  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Installer Python3
      apt:
        name: python3
        state: present

    - name: Installer Python3-pip
      apt:
        name: python3-pip
        state: present
